---
devmode: # exposes global variables, and does other stuff
  on: true
  playbackRate: 1
htmlBg: white # background color for letter boxing edges if aspect ratio is not 16:9
svgBg: white
hideUrlParameters: false
slideTransition:
  override: true # force slide transitions
  fadeOut: 0.25
  fadeIn: 0.25
css:
  # will be used within the init process to to add style="cursor: pointer" to the given ids
  # this uses querySelectorAll in styleDefaults.ts
  # Syntax: [id^=startsWith][id$=endsWith]
  mousePointerObjects:
    [
      '#link-s-introduction-speaker',
      '[id^=link][id$=next]',
      '[id^=link][id$=repeat]',
      '#s-yesnochoice-yellow-yes',
      '#s-yesnochoice-blue-yes',
      '#s-yesnochoice-purple-yes',
      '#s-yesnochoice-yellow-no',
      '#s-yesnochoice-blue-no',
      '#s-yesnochoice-purple-no',
      '#s-yesnotraining-a-yellow-yes',
      '#s-yesnotraining-a-blue-yes',
      '#s-yesnotraining-a-purple-yes',
      '#s-yesnotraining-a-yellow-no',
      '#s-yesnotraining-a-blue-no',
      '#s-yesnotraining-a-purple-no',
      '[id$=-left]',
      '[id$=-center]',
      '[id$=-right]',
    ]
  # will be used within the init process to to add a zoom animation on hover
  scaleOnHoverObjects:
    [
      '#link-s-introduction-speaker',
      '[id^=link][id$=next]',
      '[id^=link][id$=repeat]',
      '#s-yesnochoice-yellow-yes',
      '#s-yesnochoice-blue-yes',
      '#s-yesnochoice-purple-yes',
      '#s-yesnochoice-yellow-no',
      '#s-yesnochoice-blue-no',
      '#s-yesnochoice-purple-no',
      '#s-yesnotraining-a-yellow-yes',
      '#s-yesnotraining-a-blue-yes',
      '#s-yesnotraining-a-purple-yes',
      '#s-yesnotraining-a-yellow-no',
      '#s-yesnotraining-a-blue-no',
      '#s-yesnotraining-a-purple-no',
      '[id$=-left]',
      '[id$=-center]',
      '[id$=-right]',
    ]
  pinda: # applies for pinda and neutral pinda videos
    height: '30%' # pinda height
    left: '0' # offset from left SVG edge, use 0 for none offset, otherwise px,%, etc. (e.g., '10px')
    bottom: '0' # offset from bottom SVG edge, use 0 for none offset, otherwise px,%, etc. (e.g., '10px')

globals:
  defaultSubjectId: demo
  defaultCommunity: german
  defaultBirthday: '2100-01-01'
  adultThresholdAge: 18 # 17 = child, 18 = adult
  defaultGender: none
  defaultDataTransfer: local
  slideGapDuration: 750 # delay for most slides before transitioning to next
  playResponseFeedback: 0

procedure:
  # use exact slide ids from Illustrator for values
  # The order defines the experiment order
  # If you create a key with a sub array everything in the sub array will be randomized
  # You can nest only two levels deep
  german:
    # - s-introduction
    # - s-emojichoice
    # - s-yesnotraining-a
    # - s-yesnotraining-b
    # - s-yesnotraining-c
    # - s-yesnotraining-d
    # - s-yesnotraining-e
    # - s-leftrighttraining-a
    # - s-leftrighttraining-b
    # - s-leftrighttraining-c
    # - s-leftrighttraining-d
    # - s-namestraining
    # - s-perspectivetaking-one-a
    # - s-perspectivetaking-one-b
    # - s-perspectivetaking-one-c
    # - s-perspectivetaking-one-d
    # - s-perspectivetaking-two-a
    # - s-perspectivetaking-two-b
    # - s-perspectivetaking-two-c
    # - s-perspectivetaking-two-d
    # - s-knowledgeaccess-a
    # - s-knowledgeaccess-b
    # - s-dogtraining
    # - s-knowledgeaccess-c
    # - s-diversedesires-e
    # - s-diversedesires-a
    # - s-diversedesires-b
    # - s-diversedesires-c
    # - s-diversedesires-d
    # - s-diversebeliefs-a
    # - s-diversebeliefs-b
    # - s-diversebeliefs-c
    # - s-parentstraining
    # - s-falsebelief-col-a
    # - s-falsebelief-col-b
    # - s-falsebelief-uc-a
    # - s-aspectuality-a
    - s-aspectuality-b
    # - s-falsebelief-ui-b
    # - s-falsebelief-two-a
    # - s-falsebelief-two-b
    - s-end

  english:
    - s-introduction
    - s-perspectivetaking-one-a
    - s-end

  kikuyu:
    - s-introduction
    - s-perspectivetaking-one-a
    - s-end

  swahili:
    - s-introduction
    - s-perspectivetaking-one-a
    - s-end

  turkish:
    - s-introduction
    - s-perspectivetaking-one-a
    - s-end
